"""

LSTM Tabanlı bir dil modeli ile metin üretimi gerçekleştirilecek (text generation).
Eğitim verisi olarak gemini ile oluşturulmuş türkçe günlük cümleler kullanacağız.
Model verilen bir başlangıç kelimesinden yeni kelimeler ya da cümleler üretir.

Adımlar:
    -Eğitim verisinin hazırlanması (gemini ile üretilmiş günlük türkçe cümleler)
    -Tokenizasyon işlemi gerçekleştirilecek (kelimeler sayısal vektörlere çevrilecek)
    -N-Gram dizileri oluşturulacak (dil modeli için girdi ve çıktı çiftleri hazırlanacak)
    -Padding yapılarak tüm diziler aynı uzunluğa getirilecek
    -LSTM tabanlı modelin kurulması gerçekleştirilecek
    -Modelin eğitimi gerçekleştirilecek
    -Yeni metin üretimi için fonksiyon yazılacak

"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

# ==========================================
# 1. TEK ODAKLI BÜYÜK EĞİTİM VERİ SETİ (Yazılım & Yapay Zeka)
# ==========================================
# Modelin saçmalamasını önlemek için veri seti tek bir konuya (Domain) odaklanmıştır.
# Birbiriyle sıkça yan yana gelen kelimeler sayesinde model anlamsal bir yapı kurabilir.

#Eğitim veri setinin oluşturulması
texts = [
    "Yapay zeka modelleri büyük veri kümeleri üzerinde eğitilir.",
    "Makine öğrenmesi algoritmaları verilerden örüntüler öğrenebilir.",
    "Derin öğrenme karmaşık problemleri çözmek için güçlü bir yöntemdir.",
    "Sinir ağları çok katmanlı yapılar kullanarak temsil öğrenir.",
    "Transformer mimarisi doğal dil işleme alanında yaygın olarak kullanılır.",
    "Bir modelin başarısı eğitim verisinin kalitesine bağlıdır.",
    "Etiketlenmiş veriler denetimli öğrenme için gereklidir.",
    "Denetimsiz öğrenme veri içindeki gizli yapıları keşfetmeyi amaçlar.",
    "Pekiştirmeli öğrenme ödül mekanizması ile karar vermeyi geliştirir.",
    "Model eğitimi sırasında kayıp değeri sürekli takip edilir.",
    "Doğru optimizer seçimi model performansını etkileyebilir.",
    "Adam optimizasyon algoritması birçok projede tercih edilir.",
    "Gradient descent parametreleri güncellemek için kullanılır.",
    "Epoch sayısı modelin öğrenme sürecini belirleyen önemli bir parametredir.",
    "Batch size eğitim süresini ve doğruluğu etkileyebilir.",
    "Aşırı öğrenme modelin genelleme yeteneğini azaltabilir.",
    "Eksik öğrenme modelin veriyi yeterince temsil edememesine neden olur.",
    "Dropout yöntemi aşırı öğrenmeyi azaltmaya yardımcı olur.",
    "Batch normalization eğitim sürecini daha kararlı hale getirebilir.",
    "Doğrulama verisi model performansını değerlendirmek için kullanılır.",
    "Test verisi eğitim sürecine dahil edilmemelidir.",
    "Precision değeri doğru pozitif tahminlerin oranını gösterir.",
    "Recall değeri kaç gerçek pozitif örneğin yakalandığını ifade eder.",
    "F1 skoru precision ve recall değerlerini dengeler.",
    "Confusion matrix sınıflandırma sonuçlarını analiz etmeyi kolaylaştırır.",
    "ROC eğrisi sınıflandırma başarısını değerlendirmede kullanılabilir.",
    "AUC değeri model performansını özetleyen önemli bir metriktir.",
    "Veri ön işleme model başarısını önemli ölçüde etkiler.",
    "Eksik veriler uygun yöntemlerle doldurulmalıdır.",
    "Aykırı değerler model sonuçlarını olumsuz etkileyebilir.",
    "Özellik mühendisliği başarılı modeller oluşturmanın önemli bir parçasıdır.",
    "Normalizasyon farklı ölçeklerdeki verileri uyumlu hale getirir.",
    "Standardizasyon sayısal özellikleri ortak bir ölçeğe taşır.",
    "Kategorik veriler sayısal forma dönüştürülebilir.",
    "One hot encoding kategorik değişkenleri temsil etmek için kullanılır.",
    "Embedding katmanları kelimeleri yoğun vektörlere dönüştürür.",
    "Tokenization metni küçük anlamlı parçalara ayırır.",
    "Kelime gömme yöntemleri anlamsal ilişkileri öğrenebilir.",
    "Transformer modelleri attention mekanizmasını kullanır.",
    "Self attention uzun bağımlılıkları öğrenmeyi kolaylaştırır.",
    "Positional encoding kelime sırasını modele aktarır.",
    "Büyük dil modelleri milyarlarca parametre içerebilir.",
    "Fine tuning önceden eğitilmiş modelleri belirli görevlere uyarlamayı sağlar.",
    "Transfer learning eğitim süresini azaltabilir.",
    "Prompt engineering modelden daha iyi sonuç almak için kullanılabilir.",
    "Sıfır örnek öğrenme bazı görevlerde etkili olabilir.",
    "Az örnek öğrenme sınırlı veri ile başarılı sonuçlar verebilir.",
    "Veri artırma yöntemleri eğitim kümesini genişletebilir.",
    "Sentiment analizi metinlerin duygu durumunu belirlemeyi amaçlar.",
    "Metin sınıflandırma doğal dil işlemenin temel problemlerinden biridir.",
    "Adlandırılmış varlık tanıma önemli bilgi parçalarını belirler.",
    "Makine çevirisi transformer modelleri sayesinde gelişmiştir.",
    "Soru cevap sistemleri büyük dil modellerinden yararlanabilir.",
    "Metin özetleme bilgi yoğunluğunu azaltmayı hedefler.",
    "Konuşma tanıma sistemleri derin öğrenme kullanabilir.",
    "Ses sentezi yapay zekanın önemli uygulamalarından biridir.",
    "Bilgisayarlı görü alanında CNN modelleri yaygın olarak kullanılır.",
    "Evrişimsel sinir ağları görüntü özelliklerini otomatik öğrenebilir.",
    "Resim sınıflandırma bilgisayarlı görü problemlerinden biridir.",
    "Nesne tespiti görüntülerdeki nesnelerin yerini belirler.",
    "Segmentasyon her pikseli ayrı bir sınıfa atayabilir.",
    "Yüz tanıma sistemleri derin öğrenmeden yararlanır.",
    "Optik karakter tanıma metinleri dijital ortama aktarabilir.",
    "Otomatik etiketleme veri hazırlama sürecini hızlandırabilir.",
    "Zaman serisi tahmini geçmiş verilere dayanır.",
    "Anomali tespiti beklenmeyen davranışları belirlemeye yardımcı olur.",
    "Kümeleme algoritmaları benzer örnekleri gruplandırır.",
    "K means en bilinen kümeleme algoritmalarından biridir.",
    "DBSCAN yoğunluk tabanlı kümeleme yapabilir.",
    "Hiyerarşik kümeleme veri ilişkilerini ortaya çıkarabilir.",
    "Karar ağaçları yorumlanabilir modeller oluşturabilir.",
    "Random forest birçok karar ağacını birlikte kullanır.",
    "Gradient boosting güçlü tahmin modelleri oluşturabilir.",
    "XGBoost yüksek performanslı bir boosting algoritmasıdır.",
    "LightGBM büyük veri kümelerinde hızlı çalışabilir.",
    "CatBoost kategorik verilerle başarılı sonuçlar verebilir.",
    "Lojistik regresyon ikili sınıflandırmada sık kullanılır.",
    "Lineer regresyon sürekli değer tahmini yapabilir.",
    "Destek vektör makineleri karmaşık sınırlar öğrenebilir.",
    "Naive Bayes olasılık temelli bir sınıflandırma yöntemidir.",
    "K en yakın komşu algoritması benzer örnekleri kullanır.",
    "Boyut indirgeme veri analizini kolaylaştırabilir.",
    "PCA yüksek boyutlu verileri sadeleştirebilir.",
    "t SNE görselleştirme amacıyla kullanılabilir.",
    "UMAP veri dağılımını korumaya çalışır.",
    "Model açıklanabilirliği güvenilir yapay zeka için önemlidir.",
    "SHAP değerleri özellik katkılarını gösterebilir.",
    "LIME yerel model açıklamaları oluşturabilir.",
    "Veri dengesi sınıflandırma başarısını etkileyebilir.",
    "Dengesiz veri kümeleri özel yöntemler gerektirebilir.",
    "SMOTE azınlık sınıfını artırmak için kullanılabilir.",
    "Cross validation daha güvenilir değerlendirme sağlar.",
    "K fold doğrulama yaygın bir değerlendirme yöntemidir.",
    "Hiperparametre optimizasyonu model başarısını artırabilir.",
    "Grid search farklı parametreleri sistematik olarak dener.",
    "Random search daha hızlı sonuç verebilir.",
    "Bayesian optimization akıllı parametre araması yapabilir.",
    "GPU kullanımı eğitim süresini önemli ölçüde azaltabilir.",
    "CUDA destekli ekran kartları derin öğrenmede yaygın olarak kullanılır.",
    "Tensor işlemleri paralel hesaplamaya uygundur.",
    "PyTorch dinamik hesaplama grafiği sunar.",
    "TensorFlow büyük ölçekli projelerde tercih edilebilir.",
    "Scikit learn klasik makine öğrenmesi için güçlü araçlar sunar.",
    "Hugging Face birçok hazır modeli erişilebilir hale getirir.",
    "Word embedding yöntemleri kelimeleri sayısal vektörlere dönüştürür.",
    "Contextual embedding yaklaşımları kelimenin bağlamını dikkate alır.",
    "BERT modeli çift yönlü bağlam öğrenme yeteneğine sahiptir.",
    "GPT tabanlı modeller otoregresif şekilde metin üretir.",
    "Attention mekanizması önemli kelimelere daha fazla ağırlık verir.",
    "Multi-head attention farklı temsil uzaylarını aynı anda öğrenir.",
    "Encoder-decoder yapıları çeviri görevlerinde sık kullanılır.",
    "Self-supervised learning büyük veri üzerinde etiket gerektirmez.",
    "Masked language modeling kelime tahmini üzerine kuruludur.",
    "Next token prediction büyük dil modellerinin temelidir.",
    "Transformer modelleri paralel işlem yapabilme avantajına sahiptir.",
    "RNN yapıları sıralı verilerde geçmiş bilgiyi taşır.",
    "LSTM uzun bağımlılık problemini çözmek için geliştirilmiştir.",
    "GRU yapısı LSTM'e göre daha basit bir alternatiftir.",
    "NLP modelleri metin verisini anlamak için istatistiksel yöntemler kullanır.",
    "Corpus büyük metin veri kümelerini ifade eder.",
    "Veri temizleme NLP pipeline'ın önemli bir adımıdır.",
    "Stopword removal gereksiz kelimeleri metinden çıkarır.",
    "Stemming kelimeleri köklerine indirger.",
    "Lemmatization kelimeleri anlamlı kök formuna çevirir.",
    "N-gram modelleri kelime dizilimlerini analiz eder.",
    "TF-IDF kelime önemini istatistiksel olarak ölçer.",
    "Bag of Words metni kelime frekanslarına göre temsil eder.",
    "Semantic search anlamsal benzerlik üzerinden arama yapar.",
    "Vector database embedding vektörlerini saklamak için kullanılır.",
    "FAISS benzer vektörleri hızlı şekilde bulabilir.",
    "RAG sistemleri bilgi tabanı ile LLM'leri birleştirir.",
    "Retrieval augmented generation daha doğru cevaplar üretir.",
    "Prompt tuning model davranışını yönlendirmek için kullanılır.",
    "Instruction tuning modelleri talimatları daha iyi anlamasını sağlar.",
    "Fine-tuning belirli veri setine özel model eğitimi yapar.",
    "LoRA düşük maliyetli model uyarlama yöntemidir.",
    "QLoRA quantization ile fine-tuning maliyetini düşürür.",
    "Model quantization bellek kullanımını azaltır.",
    "Pruning gereksiz model ağırlıklarını kaldırır.",
    "Knowledge distillation büyük modeli küçük modele aktarır.",
    "Edge AI modelleri cihaz üzerinde çalışacak şekilde optimize edilir.",
    "MLOps model yaşam döngüsünü yönetmeyi sağlar.",
    "Model deployment eğitilmiş modeli üretime taşır.",
    "Inference aşaması modelin tahmin yaptığı süreçtir.",
    "Latency modelin cevap verme süresini ifade eder.",
    "Throughput saniyedeki işlem miktarını belirtir.",
    "Batch inference çoklu veriyi aynı anda işler.",
    "Real time inference anlık tahmin yapmayı sağlar.",
    "Cloud GPU eğitim süreçlerini hızlandırır.",
    "Distributed training büyük modelleri parçalara böler.",
    "Data parallelism veriyi farklı GPU'lara dağıtır.",
    "Model parallelism modeli farklı parçalara ayırır.",
    "Overfitting genellikle küçük veri setlerinde görülür.",
    "Regularization teknikleri modeli genelleştirmeye zorlar.",
    "L1 regularization sparsity oluşturabilir.",
    "L2 regularization ağırlıkları küçültür.",
    "Early stopping eğitim süresini otomatik durdurur.",
    "Learning rate modelin öğrenme hızını kontrol eder.",
    "Learning rate scheduling eğitim sürecini optimize eder.",
    "Warmup stratejisi başlangıçta küçük learning rate kullanır.",
    "Gradient clipping patlayan gradient problemini önler.",
    "Activation functions modele doğrusal olmayanlık kazandırır.",
    "ReLU en yaygın aktivasyon fonksiyonlarından biridir.",
    "Sigmoid fonksiyonu çıktıyı 0 ile 1 arasına sıkıştırır.",
    "Softmax çok sınıflı problemler için kullanılır.",
    "Loss function model hatasını ölçer.",
    "Cross entropy classification problemlerinde sık kullanılır.",
    "Mean squared error regresyon problemlerinde tercih edilir.",
    "Dataset augmentation veri çeşitliliğini artırır.",
    "Image augmentation döndürme ve kırpma işlemleri içerir.",
    "Text augmentation metin verisini çeşitlendirebilir.",
    "Backtranslation veri artırma yöntemlerinden biridir.",
    "Adversarial examples modelleri yanıltmak için oluşturulur.",
    "Model robustness saldırılara karşı dayanıklılığı ifade eder.",
    "Bias modelin sistematik hatalarını gösterir.",
    "Fairness AI sistemlerinde adalet ilkesini temsil eder.",
    "Explainable AI model kararlarının anlaşılmasını sağlar.",
    "Interpretability model çıktılarının yorumlanabilirliğidir.",
    "AI ethics yapay zeka kullanımında etik kuralları içerir.",
    "Data leakage eğitim sırasında bilgi sızmasını ifade eder.",
    "Train test split veri setini bölmek için kullanılır.",
    "Cross entropy loss sınıflandırma hatasını ölçer.",
    "Multimodal AI farklı veri türlerini birlikte işler.",
    "Vision transformer görüntüleri patch'lere ayırarak işler.",
    "CLIP model görüntü ve metni aynı uzayda eşler.",
    "Diffusion models görüntü üretiminde yüksek kalite sağlar.",
    "GAN iki ağın rekabeti ile öğrenir.",
    "Generator veri üretirken discriminator doğruluk kontrolü yapar.",
    "Autoencoder veriyi sıkıştırmayı öğrenir.",
    "Latent space verinin sıkıştırılmış temsilidir.",
    "Representation learning veri özelliklerini otomatik öğrenir.",
    "Feature extraction modelin önemli bilgileri ayıklamasıdır.",
    "Anomaly detection olağandışı örnekleri tespit eder.",
    "Time series forecasting geleceği tahmin etmeye çalışır.",
    "Reinforcement learning agent çevre ile etkileşim kurar.",
    "Reward function doğru davranışı ödüllendirir.",
    "Policy optimization karar stratejisini geliştirir.",
    "Q learning değer tabanlı öğrenme yöntemidir.",
    "Deep Q Network sinir ağlarını RL ile birleştirir.",
    "AI safety modellerin güvenli çalışmasını hedefler.",
    "Hallucination büyük dil modellerinde yanlış bilgi üretimidir.",
    "Token limit modellerin işleyebileceği maksimum metindir.",
    "Context window modelin görebildiği metin uzunluğudur.",
    "Embedding similarity iki vektör arasındaki benzerliği ölçer.",
    "Cosine similarity sık kullanılan benzerlik ölçüsüdür.",
    "Nearest neighbor araması benzer veri noktalarını bulur.",
    "Clustering evaluation silhouette score ile yapılabilir.",
    "Hyperparameter tuning model performansını optimize eder.",
    "Neural architecture search otomatik model tasarımı yapar.",
    "AutoML model geliştirme sürecini otomatikleştirir.",
    "Data pipeline veriyi işleme sürecini otomatik hale getirir.",
    "Feature scaling model eğitimini stabilize eder.",
    "Min max scaling veriyi belirli aralığa sıkıştırır.",
    "Standard scaler ortalama ve varyansı normalize eder.",
    "Sparse data çoğu değeri sıfır olan veri türüdür.",
    "Dense vector yoğun sayısal temsildir.",
    "Transformer decoder metin üretiminde kullanılır.",
    "Sequence to sequence modeller giriş çıkış dizileri işler.",
    "Language modeling bir sonraki kelimeyi tahmin etmeye çalışır.",
    "Perplexity dil modelinin başarısını ölçer.",
    "BLEU skoru makine çevirisi kalitesini ölçer.",
    "ROUGE skoru özetleme performansını değerlendirir.",
    "Knowledge graph varlıklar arasındaki ilişkileri temsil eder.",
    "Graph neural networks grafik yapılar üzerinde çalışır.",
    "AI model monitoring üretimde performansı izler.",
    "Data drift veri dağılımının zamanla değişmesidir.",
    "Concept drift modelin öğrendiği ilişkilerin değişmesidir.",
    "Continuous learning modelin sürekli güncellenmesidir.",
    "Federated learning veriyi paylaşmadan eğitim yapar.",
    "Privacy preserving AI veri gizliliğini korur.",
    "Secure AI saldırılara karşı koruma sağlar.",
    "Synthetic data gerçek veriyi taklit ederek üretilir.",
    "Benchmark datasets modelleri karşılaştırmak için kullanılır.",
    "Open source ML kütüphaneleri geliştirmeyi kolaylaştırır.",
    "Model versioning farklı model sürümlerini yönetir.",
    "Experiment tracking eğitim deneylerini kaydeder.",
    "Reproducibility aynı sonuçların tekrar üretilebilmesini sağlar.",
    "AI research sürekli gelişen bir çalışma alanıdır.",
    "Transformer tabanlı modeller büyük veri üzerinde ölçeklenebilir öğrenme sağlar.",
    "Self-attention mekanizması cümledeki kelimeler arasındaki ilişkileri yakalar.",
    "Encoder katmanı girdiyi temsil uzayına dönüştürür.",
    "Decoder katmanı bu temsillerden çıktı üretir.",
    "Dil modelleri olasılıksal metin üretimi yapar.",
    "Büyük dil modelleri internet ölçeğinde veriyle eğitilir.",
    "Pretraining aşaması genel dil bilgisini öğrenmeyi sağlar.",
    "Fine-tuning aşaması modele görev özel bilgi kazandırır.",
    "Instruction dataset modelleri talimatlara daha duyarlı hale getirir.",
    "Chatbot sistemleri kullanıcı ile doğal dilde etkileşim kurar.",
    "NLP görevleri metin sınıflandırma ve anlama içerir.",
    "Named entity recognition metindeki önemli varlıkları bulur.",
    "Part of speech tagging kelimelerin dilbilgisel rollerini belirler.",
    "Dependency parsing cümle yapısını analiz eder.",
    "Semantic role labeling cümledeki anlam ilişkilerini çıkarır.",
    "Word sense disambiguation kelime anlamını bağlama göre belirler.",
    "Coreference resolution aynı varlığa referansları eşleştirir.",
    "Language models metin üretiminde temel yapı taşlarıdır.",
    "Token embedding kelimeleri sayısal vektörlere çevirir.",
    "Positional encoding sıralı bilgiyi modele ekler.",
    "Attention score hangi kelimenin önemli olduğunu belirler.",
    "Scaled dot product attention Transformer'da kullanılır.",
    "Multi head attention farklı alt uzayları öğrenir.",
    "Layer normalization eğitim sürecini stabilize eder.",
    "Residual connections derin ağlarda bilgi kaybını azaltır.",
    "Gradient descent optimizasyonun temel yöntemidir.",
    "Stochastic gradient descent mini batchlerle çalışır.",
    "Adaptive learning rate optimizasyonu hızlandırabilir.",
    "Loss landscape modelin öğrenme zorluğunu gösterir.",
    "Overfitting eğitim verisine aşırı uyumdur.",
    "Underfitting modelin yetersiz öğrenmesidir.",
    "Bias variance tradeoff model genellemesini etkiler.",
    "Regularization teknikleri model karmaşıklığını kontrol eder.",
    "Dropout nöronları rastgele devre dışı bırakır.",
    "Weight decay model ağırlıklarını küçültür.",
    "Early stopping aşırı öğrenmeyi engeller.",
    "Cross validation modelin güvenilirliğini artırır.",
    "K fold validation veri setini parçalara böler.",
    "Stratified sampling sınıf dağılımını korur.",
    "Data augmentation veri çeşitliliğini artırır.",
    "Synthetic data üretimi veri eksikliğini azaltabilir.",
    "Feature selection önemli değişkenleri seçer.",
    "Dimensionality reduction veri boyutunu azaltır.",
    "PCA varyansı koruyarak boyut indirger.",
    "t-SNE yüksek boyutlu veriyi görselleştirir.",
    "UMAP lokal yapıyı korumaya çalışır.",
    "Clustering benzer verileri gruplar.",
    "K-means centroid tabanlı bir algoritmadır.",
    "Hierarchical clustering ağaç yapısı oluşturur.",
    "DBSCAN yoğunluk tabanlı kümeleme yapar.",
    "Classification kategorik çıktı tahmin eder.",
    "Regression sürekli değer tahmin eder.",
    "Supervised learning etiketli veri kullanır.",
    "Unsupervised learning etiketsiz veriden öğrenir.",
    "Reinforcement learning ödül tabanlı öğrenmedir.",
    "Agent çevre ile etkileşim kurar.",
    "Environment öğrenme ortamını temsil eder.",
    "Reward function doğru davranışı ödüllendirir.",
    "Policy agentin davranış stratejisidir.",
    "Q-learning değer tabanlı RL yöntemidir.",
    "Deep reinforcement learning sinir ağları kullanır.",
    "Neural networks katmanlı hesaplama yapılarıdır.",
    "Backpropagation hata geri yayılımıdır.",
    "Activation function doğrusal olmayanlık ekler.",
    "ReLU negatif değerleri sıfırlar.",
    "Sigmoid çıktıyı 0 ile 1 arasında sınırlar.",
    "Tanh fonksiyonu -1 ile 1 arasında değer üretir.",
    "Softmax olasılık dağılımı üretir.",
    "Log loss sınıflandırma hatasını ölçer.",
    "Mean absolute error regresyon için kullanılır.",
    "Root mean squared error hata büyüklüğünü ölçer.",
    "Model evaluation performans ölçümüdür.",
    "Confusion matrix sınıflandırma sonuçlarını gösterir.",
    "Precision doğru pozitif oranını ifade eder.",
    "Recall gerçek pozitifleri yakalama oranıdır.",
    "F1 score dengeleyici metriktir.",
    "ROC curve model performansını gösterir.",
    "AUC değerinin yüksek olması iyidir.",
    "Feature engineering model performansını artırır.",
    "Data preprocessing ham veriyi hazırlar.",
    "Normalization veriyi ölçeklendirir.",
    "Standardization ortalamayı sıfıra çeker.",
    "Encoding kategorik veriyi sayısallaştırır.",
    "One hot encoding kategorileri vektörleştirir.",
    "Label encoding sınıfları sayıya çevirir.",
    "Embeddings anlamsal ilişkileri öğrenir.",
    "Vector space model metni sayısal uzaya taşır.",
    "Similarity search benzer verileri bulur.",
    "Cosine similarity vektör benzerliği ölçer.",
    "Euclidean distance mesafe ölçümüdür.",
    "Nearest neighbors benzer örnekleri kullanır.",
    "Information retrieval arama sistemlerinin temelidir.",
    "Search engines NLP teknikleri kullanır.",
    "Question answering sistemleri doğru cevap üretir.",
    "Machine translation diller arası çeviri yapar.",
    "Text summarization metni kısaltır.",
    "Sentiment analysis duygu durumunu belirler.",
    "Topic modeling metin konularını keşfeder.",
    "Latent Dirichlet Allocation popüler bir yöntemdir.",
    "Word2Vec kelime embedding üretir.",
    "GloVe global istatistikleri kullanır.",
    "FastText alt kelime yapısını dikkate alır.",
    "Transformer models modern NLP'nin temelidir.",
    "BERT bidirectional context öğrenir.",
    "GPT autoregressive dil modelidir.",
    "T5 text to text framework kullanır.",
    "Large language models ölçeklenebilir yapıdadır.",
    "Prompt engineering model davranışını yönlendirir.",
    "Chain of thought reasoning model performansını artırabilir.",
    "Few shot learning az veri ile öğrenmeyi sağlar.",
    "Zero shot learning örnek olmadan genelleme yapar.",
    "Transfer learning bilgi aktarımı yapar.",
    "Multi task learning aynı anda birden fazla görev öğrenir.",
    "Model compression modelleri küçültür.",
    "Knowledge distillation öğretmen öğrenci yapısıdır.",
    "Quantization model boyutunu azaltır.",
    "Pruning gereksiz ağırlıkları kaldırır.",
    "Inference modelin tahmin aşamasıdır.",
    "Training modelin öğrenme aşamasıdır.",
    "Dataset veri topluluğunu ifade eder.",
    "Label supervision öğrenmeyi yönlendirir.",
    "Unlabeled data etiketsiz veridir.",
    "Data pipeline veriyi işler ve taşır.",
    "ML pipeline model geliştirme sürecidir.",
    "MLOps model yaşam döngüsünü yönetir.",
    "Model deployment modeli üretime alır.",
    "Monitoring model performansını izler.",
    "Drift detection veri değişimini tespit eder.",
    "AI systems sürekli iyileştirme gerektirir.",
    "Scalability büyük veri ile çalışabilme yeteneğidir.",
    "Distributed systems hesaplamayı böler.",
    "GPU acceleration eğitim süresini hızlandırır.",
    "TPU özel AI işlem birimidir.",
    "Cloud computing uzak sunucularla işlem yapar.",
    "Edge computing cihaz üzerinde işlem yapar.",
    "Federated learning gizliliği korur.",
    "Privacy preserving ML veri güvenliğini sağlar.",
    "Explainable AI kararları açıklar.",
    "AI ethics sorumlu kullanım prensiplerini içerir.",
    "Bias detection adaletsizliği tespit eder.",
    "Fairness metrics model adaletini ölçer.",
    "Robust AI saldırılara karşı dayanıklıdır.",
    "Adversarial attack modelleri yanıltabilir.",
    "Adversarial training dayanıklılığı artırır.",
    "Synthetic datasets gerçek veriyi taklit eder.",
    "Data labeling eğitim için gereklidir.",
    "Crowdsourcing veri etiketleme yöntemi olabilir.",
    "Benchmark datasets karşılaştırma sağlar.",
    "Open source ML araçları geliştirmeyi kolaylaştırır.",
    "Research papers AI ilerlemesini hızlandırır.",
    "Experiment tracking deneyleri kaydeder.",
    "Version control modelleri yönetir.",
    "Reproducibility bilimsel çalışmalar için önemlidir.",
    "AI development sürekli gelişen bir süreçtir.",
    "Transformer modelleri büyük ölçekli metin verileri üzerinde eğitildiğinde daha güçlü genelleme yapabilir.",
    "Self-attention mekanizması uzun metinlerde bağlam ilişkilerini korumaya yardımcı olur.",
    "Encoder-decoder yapıları özellikle makine çevirisi görevlerinde başarılıdır.",
    "BERT modeli maskelenmiş kelimeleri tahmin ederek bağlamı öğrenir.",
    "GPT modelleri sıradaki tokenı tahmin ederek metin üretir.",
    "Large language models çok sayıda parametre ile karmaşık dil yapısını öğrenir.",
    "Pretraining süreci modelin genel dil bilgisini kazanmasını sağlar.",
    "Fine-tuning modeli belirli bir göreve uyarlamak için kullanılır.",
    "Instruction tuning modellerin kullanıcı komutlarını daha iyi anlamasını sağlar.",
    "RLHF insan geri bildirimi ile model davranışını optimize eder.",
    "Tokenization metni daha küçük birimlere bölerek işlemeyi kolaylaştırır.",
    "Subword tokenization nadir kelimeleri daha iyi temsil eder.",
    "Byte pair encoding kelime parçalarını birleştirerek sözlük oluşturur.",
    "WordPiece algoritması kelime parçalama için yaygın kullanılır.",
    "Embedding katmanı kelimeleri yoğun vektörlere dönüştürür.",
    "Contextual embeddings kelimenin bağlama göre anlamını değiştirir.",
    "Static embeddings her kelime için sabit vektör üretir.",
    "Attention score hangi kelimenin daha önemli olduğunu belirler.",
    "Multi-head attention farklı ilişkileri paralel şekilde öğrenir.",
    "Positional encoding kelimelerin sırasını modele ekler.",
    "Residual connections derin ağlarda bilgi akışını kolaylaştırır.",
    "Layer normalization eğitim sürecini daha stabil hale getirir.",
    "Feed forward network Transformer içinde doğrusal olmayan dönüşüm sağlar.",
    "Softmax fonksiyonu olasılık dağılımı üretmek için kullanılır.",
    "Cross entropy loss sınıflandırma problemlerinde yaygın bir kayıp fonksiyonudur.",
    "Gradient descent model parametrelerini optimize eder.",
    "Backpropagation hata sinyalini geriye doğru yayar.",
    "Learning rate modelin öğrenme hızını kontrol eder.",
    "Learning rate scheduling eğitim sürecini dinamik hale getirir.",
    "Overfitting modelin eğitim verisine aşırı uyum sağlamasıdır.",
    "Underfitting modelin yeterince öğrenememesidir.",
    "Regularization yöntemleri model karmaşıklığını azaltır.",
    "Dropout rastgele nöronları devre dışı bırakarak genelleme sağlar.",
    "Weight decay model ağırlıklarını kontrol altında tutar.",
    "Early stopping eğitim sürecini erken sonlandırabilir.",
    "Cross validation model performansını daha güvenilir ölçer.",
    "K fold cross validation veri setini alt parçalara böler.",
    "Stratified sampling sınıf dağılımını korur.",
    "Data augmentation veri çeşitliliğini artırır.",
    "Noise injection modele dayanıklılık kazandırabilir.",
    "Feature selection en önemli değişkenleri seçer.",
    "Feature extraction veriden anlamlı temsil çıkarır.",
    "Dimensionality reduction veri boyutunu azaltır.",
    "Principal component analysis varyansı koruyarak indirgeme yapar.",
    "t-SNE yüksek boyutlu veriyi görselleştirir.",
    "UMAP lokal ve global yapıyı korumaya çalışır.",
    "Clustering algoritmaları benzer veri noktalarını gruplar.",
    "K-means centroid tabanlı kümeleme yöntemidir.",
    "Hierarchical clustering ağaç yapısı oluşturur.",
    "DBSCAN yoğunluk tabanlı kümeleme yapar.",
    "Classification algoritmaları kategorik çıktı üretir.",
    "Regression algoritmaları sürekli değer tahmin eder.",
    "Supervised learning etiketli verilerle çalışır.",
    "Unsupervised learning etiketsiz verilerden yapı öğrenir.",
    "Semi supervised learning az etiketli veri ile çalışır.",
    "Reinforcement learning ödül sinyali ile öğrenme yapar.",
    "Agent çevre ile etkileşim kurarak öğrenir.",
    "Environment öğrenme ortamını temsil eder.",
    "Reward function doğru davranışları ödüllendirir.",
    "Policy agentin karar verme stratejisidir.",
    "Value function gelecekteki ödülleri tahmin eder.",
    "Q learning değer tabanlı öğrenme algoritmasıdır.",
    "Deep Q network sinir ağlarını RL ile birleştirir.",
    "Policy gradient yöntemleri doğrudan strateji öğrenir.",
    "Actor critic yöntemleri iki modeli birlikte kullanır.",
    "Neural networks katmanlı öğrenme yapılarıdır.",
    "Activation functions modele doğrusal olmayanlık ekler.",
    "ReLU negatif değerleri sıfırlar ve hızlı çalışır.",
    "Sigmoid fonksiyonu olasılık üretmek için kullanılır.",
    "Tanh fonksiyonu çıktıları -1 ile 1 arasına sıkıştırır.",
    "Softmax çok sınıflı problemlerde kullanılır.",
    "Loss function model hatasını ölçer.",
    "Mean squared error regresyon için kullanılır.",
    "Mean absolute error hata büyüklüğünü ölçer.",
    "Root mean squared error büyük hataları daha fazla cezalandırır.",
    "Evaluation metrics model performansını ölçer.",
    "Confusion matrix sınıflandırma sonuçlarını analiz eder.",
    "Precision doğru pozitiflerin oranını gösterir.",
    "Recall gerçek pozitiflerin yakalanma oranıdır.",
    "F1 score precision ve recall dengesini sağlar.",
    "ROC curve model başarısını görselleştirir.",
    "AUC değeri modelin ayrım gücünü ölçer.",
    "Feature engineering model performansını artırır.",
    "Data preprocessing ham veriyi kullanılabilir hale getirir.",
    "Normalization veriyi belirli aralığa ölçekler.",
    "Standardization ortalama ve varyansı düzenler.",
    "Encoding kategorik veriyi sayısal hale getirir.",
    "One hot encoding kategorileri vektöre dönüştürür.",
    "Label encoding sınıfları sayısal değerlere çevirir.",
    "Embeddings anlamsal benzerlikleri yakalar.",
    "Vector space model metni matematiksel uzaya taşır.",
    "Similarity search benzer içerikleri bulur.",
    "Cosine similarity vektörler arasındaki açıyı ölçer.",
    "Euclidean distance iki nokta arasındaki mesafeyi hesaplar.",
    "Nearest neighbor algoritmaları benzer örnekleri kullanır.",
    "Information retrieval arama sistemlerinin temelidir.",
    "Search engines kullanıcı sorgularını işler.",
    "Question answering sistemleri doğru yanıt üretmeye çalışır.",
    "Machine translation metni bir dilden diğerine çevirir.",
    "Text summarization uzun metinleri özetler.",
    "Sentiment analysis metin duygusunu belirler.",
    "Topic modeling metinlerdeki konuları keşfeder.",
    "Latent Dirichlet Allocation metin modelleme yöntemidir.",
    "Word2Vec kelimeleri vektör uzayına yerleştirir.",
    "GloVe global kelime istatistiklerini kullanır.",
    "FastText alt kelime yapısını dikkate alır.",
    "Transformer architecture modern NLP'nin temelidir.",
    "BERT bidirectional context öğrenir.",
    "GPT autoregressive dil modelidir.",
    "T5 text-to-text yaklaşımı kullanır.",
    "Large language models çok geniş veriyle eğitilir.",
    "Prompt engineering model çıktısını yönlendirmek için kullanılır.",
    "Chain of thought reasoning adım adım düşünmeyi teşvik eder.",
    "Few shot learning az örnekle öğrenme sağlar.",
    "Zero shot learning örnek olmadan genelleme yapar.",
    "Transfer learning bilgiyi bir görevden diğerine aktarır.",
    "Multi task learning aynı modelle birden fazla görev çözer.",
    "Model compression modelleri daha küçük hale getirir.",
    "Knowledge distillation büyük modelden küçük modele bilgi aktarır.",
    "Quantization model ağırlıklarını küçültür.",
    "Pruning gereksiz bağlantıları kaldırır.",
    "Inference modelin tahmin üretme aşamasıdır.",
    "Training modelin öğrenme sürecidir.",
    "Dataset veri örneklerinden oluşur.",
    "Label supervised learning için gereklidir.",
    "Unlabeled data etiketsiz veri anlamına gelir.",
    "Data pipeline veriyi işleyen süreçtir.",
    "ML pipeline model geliştirme adımlarını içerir.",
    "MLOps model yaşam döngüsünü yönetir.",
    "Model deployment modeli üretim ortamına taşır.",
    "Monitoring model performansını sürekli izler.",
    "Data drift veri dağılımının değişmesidir.",
    "Concept drift öğrenilen ilişkilerin değişmesidir.",
    "AI systems sürekli güncellenmeyi gerektirir.",
    "Scalability büyük veriyle çalışma yeteneğidir.",
    "Distributed training hesaplamayı birden fazla cihaza böler.",
    "GPU acceleration eğitim süresini hızlandırır.",
    "TPU yapay zeka için optimize edilmiş donanımdır.",
    "Cloud computing uzak sunucularda işlem yapmayı sağlar.",
    "Edge computing cihaz üzerinde işlem yapar.",
    "Federated learning veriyi paylaşmadan öğrenme sağlar.",
    "Privacy preserving ML veri gizliliğini korur.",
    "Explainable AI model kararlarını açıklar.",
    "AI ethics yapay zekanın etik kullanımını kapsar.",
    "Bias detection modeldeki adaletsizlikleri bulur.",
    "Fairness metrics model adaletini ölçer.",
    "Robust AI saldırılara karşı dayanıklı modeller üretir.",
    "Adversarial attacks modelleri yanıltmayı amaçlar.",
    "Adversarial training modeli saldırılara karşı güçlendirir.",
    "Synthetic data gerçek veriyi taklit eder.",
    "Data labeling model eğitimi için gereklidir.",
    "Crowdsourcing veri etiketleme yöntemidir.",
    "Benchmark datasets modelleri karşılaştırmak için kullanılır.",
    "Open source ML araçları geliştirmeyi kolaylaştırır.",
    "Experiment tracking deneyleri kaydeder.",
    "Model versioning farklı sürümleri yönetir.",
    "Reproducibility aynı sonuçların tekrar üretilebilmesini sağlar.",
    "AI research sürekli gelişen bir alandır.",
    "Data preprocessing makine öğrenmesi sürecinin en kritik adımlarından biridir.",
    "Ham veri genellikle model eğitimi için doğrudan kullanılamaz.",
    "Eksik değerler model performansını ciddi şekilde etkileyebilir.",
    "Missing value imputation veri setindeki boşlukları doldurmak için kullanılır.",
    "Mean imputation sayısal eksik değerleri ortalama ile doldurur.",
    "Median imputation aykırı değerlere karşı daha dayanıklıdır.",
    "Mode imputation kategorik verilerde en sık kullanılan değeri kullanır.",
    "Outlier detection veri içindeki anormal noktaları tespit eder.",
    "Z-score yöntemi aykırı değerleri istatistiksel olarak belirler.",
    "IQR yöntemi çeyrekler arası aralığı kullanarak outlier tespit eder.",
    "Feature scaling modellerin daha stabil öğrenmesini sağlar.",
    "Normalization veriyi 0 ile 1 arasına ölçekler.",
    "Standardization veriyi ortalama 0 ve standart sapma 1 olacak şekilde dönüştürür.",
    "Min-max scaling veriyi belirli bir aralığa sıkıştırır.",
    "Robust scaling medyan ve IQR kullanarak ölçekleme yapar.",
    "Encoding kategorik değişkenleri sayısal forma dönüştürür.",
    "Label encoding kategorilere tamsayı değerler atar.",
    "One hot encoding her kategoriyi ayrı bir binary sütun haline getirir.",
    "Ordinal encoding sıralı kategoriler için kullanılır.",
    "Target encoding kategorileri hedef değişkene göre kodlar.",
    "Feature engineering model performansını artırmak için yeni özellikler üretir.",
    "Polynomial features doğrusal olmayan ilişkileri yakalamaya yardımcı olur.",
    "Feature selection gereksiz değişkenleri elemek için kullanılır.",
    "Filter methods istatistiksel ölçütlere göre özellik seçer.",
    "Wrapper methods model performansına göre feature seçimi yapar.",
    "Embedded methods model içinde feature selection gerçekleştirir.",
    "PCA boyut indirgeme için kullanılan temel yöntemlerden biridir.",
    "SVD matris ayrıştırma tekniklerinden biridir.",
    "Dimensionality reduction veri karmaşıklığını azaltır.",
    "Encoding layer sinir ağlarında kategorik veriyi temsil etmek için kullanılabilir.",
    "Embedding layer kelimeleri dense vektörlere dönüştürür.",
    "Word embeddings semantik benzerliği yakalamaya yardımcı olur.",
    "Contextual embeddings kelimenin bağlamına göre değişir.",
    "Static embeddings her kelime için sabit vektör üretir.",
    "Feature vector modelin girişini temsil eder.",
    "Design matrix makine öğrenmesi için kullanılan veri matrisidir.",
    "Train test split veri setini eğitim ve test olarak böler.",
    "Validation set model tuning için kullanılır.",
    "Cross validation modelin genelleme gücünü ölçer.",
    "K fold cross validation veri setini K parçaya böler.",
    "Stratified split sınıf dağılımını koruyarak veri böler.",
    "Shuffle split veriyi rastgele böler.",
    "Pipeline veri ön işleme adımlarını otomatikleştirir.",
    "Sklearn pipeline preprocessing ve model adımlarını birleştirir.",
    "Data leakage modelin yanlış bilgi öğrenmesine neden olur.",
    "Leakage training sırasında test bilgisinin sızmasıdır.",
    "Imbalanced dataset sınıf dağılımı eşit olmayan veri setidir.",
    "Oversampling azınlık sınıfını artırma yöntemidir.",
    "Undersampling çoğunluk sınıfını azaltır.",
    "SMOTE sentetik veri üreterek denge sağlar.",
    "Feature importance modelde hangi değişkenlerin önemli olduğunu gösterir.",
    "Permutation importance özelliklerin etkisini ölçer.",
    "Correlation matrix değişkenler arasındaki ilişkiyi gösterir.",
    "Multicollinearity değişkenler arasında yüksek korelasyon olmasıdır.",
    "Regularization overfitting'i azaltmak için kullanılır.",
    "L1 regularization sparsity üretir.",
    "L2 regularization ağırlıkları küçültür.",
    "Elastic net L1 ve L2'nin birleşimidir.",
    "Loss function model hatasını ölçer.",
    "Cost function optimizasyon için kullanılan hata fonksiyonudur.",
    "Gradient descent parametreleri iteratif olarak günceller.",
    "Stochastic gradient descent mini batch kullanır.",
    "Batch gradient descent tüm veri ile çalışır.",
    "Mini batch gradient descent denge sağlar.",
    "Learning rate modelin öğrenme hızını belirler.",
    "Learning rate scheduling eğitim sürecini optimize eder.",
    "Warmup learning rate başlangıçta küçük değer kullanır.",
    "Optimizer parametre güncelleme algoritmasıdır.",
    "Adam optimizer adaptif öğrenme oranı kullanır.",
    "RMSprop gradientleri normalize eder.",
    "Momentum optimizasyonu hızlandırır.",
    "Backpropagation hata gradyanlarını hesaplar.",
    "Forward propagation modelin tahmin üretme aşamasıdır.",
    "Activation function modele doğrusal olmayanlık kazandırır.",
    "ReLU negatif değerleri sıfırlar.",
    "Leaky ReLU küçük negatif değerleri korur.",
    "Sigmoid binary classification için kullanılır.",
    "Softmax çok sınıflı çıktılar üretir.",
    "Loss convergence modelin öğrenme stabilitesini gösterir.",
    "Epoch tüm veri setinin bir kez işlenmesidir.",
    "Batch size her adımda kullanılan veri miktarıdır.",
    "Iteration bir batch'in işlenme adımıdır.",
    "Early stopping overfitting'i önlemek için kullanılır.",
    "Model checkpointing eğitim sırasında kayıt alır.",
    "Hyperparameter tuning model performansını artırır.",
    "Grid search tüm kombinasyonları dener.",
    "Random search rastgele kombinasyonlar dener.",
    "Bayesian optimization akıllı arama yapar.",
    "Model evaluation performans ölçüm sürecidir.",
    "Accuracy doğru tahmin oranını gösterir.",
    "Precision doğru pozitif oranını ifade eder.",
    "Recall gerçek pozitifleri yakalama başarısıdır.",
    "F1 score precision ve recall dengesidir.",
    "ROC AUC model ayrım gücünü ölçer.",
    "Confusion matrix sınıflandırma sonuçlarını gösterir.",
    "Log loss olasılıksal hatayı ölçer.",
    "MAE ortalama mutlak hatadır.",
    "MSE kare hata ortalamasıdır.",
    "RMSE hata büyüklüğünü daha hassas ölçer.",
    "Bias variance tradeoff model karmaşıklığını açıklar.",
    "Generalization modelin yeni veriye uyumudur.",
    "Model drift zamanla performans düşüşüdür.",
    "Data drift veri dağılımının değişmesidir.",
    "Concept drift hedef değişken ilişkilerinin değişmesidir.",
    "Feature pipeline veri hazırlama sürecidir.",
    "ETL pipeline extract transform load sürecidir.",
    "Data transformation veriyi modele uygun hale getirir.",
    "Vectorization metni sayısal vektöre çevirir.",
    "TF-IDF kelime önemini istatistiksel olarak hesaplar.",
    "Bag of words metni kelime frekansına çevirir.",
    "N-gram kelime dizilimlerini modellemek için kullanılır.",
    "Sliding window zaman serilerinde veri oluşturur.",
    "Time series preprocessing özel teknikler gerektirir.",
    "Scaling methods model stabilitesini artırır.",
    "Data normalization modelin daha hızlı öğrenmesini sağlar.",
    "Preprocessing pipeline model başarısının temelidir.",
    "Clean data daha iyi model performansı sağlar.",
"Veri kalitesi makine öğrenmesi modelinin başarısını doğrudan etkiler.",
    "Kötü veri iyi bir modeli bile başarısız hale getirebilir.",
    "Dataset model eğitimi için kullanılan veri koleksiyonudur.",
    "Veri toplama süreci modelin temelini oluşturur.",
    "Labeling süreci veriye doğru etiketlerin atanmasını sağlar.",
    "Yanlış etiketlenmiş veri modelin öğrenmesini bozar.",
    "Noisy data model performansını düşürebilir.",
    "Veri temizleme ham veriyi analiz için uygun hale getirir.",
    "Duplicate records veri setinde yanlılığa neden olabilir.",
    "Veri deduplication tekrar eden kayıtları kaldırır.",
    "Missing values veri bütünlüğünü bozar.",
    "Imputation eksik verileri doldurma yöntemidir.",
    "Veri dağılımı modelin genelleme yeteneğini etkiler.",
    "Train dataset modelin öğrenmesi için kullanılır.",
    "Test dataset modelin performansını ölçmek için kullanılır.",
    "Validation dataset model ayarlama sürecinde kullanılır.",
    "Data split işlemi veri setini farklı parçalara ayırır.",
    "Stratified split sınıf dağılımını korur.",
    "Random split veriyi rastgele böler.",
    "Data leakage test bilgisinin eğitim verisine sızmasıdır.",
    "Leakage modelin gerçek performansını olduğundan yüksek gösterir.",
    "Temporal leakage zaman bilgisinin yanlış kullanımıdır.",
    "Feature leakage hedef değişkenin dolaylı olarak verilmesidir.",
    "Data drift veri dağılımının zamanla değişmesidir.",
    "Concept drift hedef değişken ilişkilerinin değişmesidir.",
    "Drift detection model performansını izlemek için kullanılır.",
    "Dataset versioning veri seti değişimlerini takip eder.",
    "Data version control veri seti yönetimini kolaylaştırır.",
    "Data pipeline verinin işlenme sürecini otomatikleştirir.",
    "ETL süreci extract transform load adımlarını içerir.",
    "Data ingestion verinin sisteme alınma sürecidir.",
    "Data storage verinin güvenli şekilde saklanmasını sağlar.",
    "Data lake ham verinin depolandığı yapıdır.",
    "Data warehouse analiz için optimize edilmiş veri deposudur.",
    "Structured data tablo formatındaki veridir.",
    "Unstructured data metin, görüntü ve ses gibi verileri içerir.",
    "Semi structured data JSON ve XML gibi formatlardır.",
    "Tabular data satır ve sütunlardan oluşur.",
    "Time series data zamana bağlı veri türüdür.",
    "Streaming data sürekli akan veri akışıdır.",
    "Batch data belirli aralıklarla işlenen veridir.",
    "Real time data anlık işlenen veridir.",
    "Data annotation veriye etiket ekleme işlemidir.",
    "Human in the loop etiketleme sürecine insan müdahalesidir.",
    "Weak supervision az kaliteli etiketlerle öğrenmeyi ifade eder.",
    "Self supervised learning etiket üretimini verinin kendisinden yapar.",
    "Synthetic data gerçek veriyi taklit ederek üretilir.",
    "Data augmentation veri çeşitliliğini artırır.",
    "Noise injection veriye rastgele bozulma ekler.",
    "Outlier data normal dağılımdan sapmış örneklerdir.",
    "Data normalization veriyi ölçeklendirme işlemidir.",
    "Data standardization ortalama ve varyansı düzenler.",
    "Min max scaling veriyi belirli aralığa çeker.",
    "Z score scaling standart sapmaya göre ölçekler.",
    "Robust scaling aykırı değerlere karşı dayanıklıdır.",
    "Feature distribution değişkenlerin istatistiksel dağılımıdır.",
    "Class imbalance veri setindeki sınıf dengesizliğidir.",
    "Oversampling az sınıfı çoğaltma yöntemidir.",
    "Undersampling fazla sınıfı azaltma yöntemidir.",
    "SMOTE sentetik örnek üretme tekniğidir.",
    "Data sampling veri alt kümesi seçme işlemidir.",
    "Random sampling rastgele veri seçimi yapar.",
    "Systematic sampling belirli aralıklarla veri seçer.",
    "Data bias modelin önyargılı öğrenmesine neden olabilir.",
    "Sampling bias veri toplama sürecindeki hatalardan kaynaklanır.",
    "Measurement bias yanlış ölçümden kaynaklanır.",
    "Selection bias verinin temsil gücünü bozar.",
    "Data lineage verinin kaynağını izlemeyi sağlar.",
    "Data governance veri yönetim kurallarını belirler.",
    "Data privacy kullanıcı verisinin korunmasını sağlar.",
    "Data anonymization kişisel bilgileri gizler.",
    "PII sensitive personal information anlamına gelir.",
    "Data compliance veri kullanımının yasalara uygunluğudur.",
    "GDPR Avrupa veri koruma düzenlemesidir.",
    "Data labeling consistency tutarlı etiketleme sağlar.",
    "Annotation guidelines etiketleme kurallarını belirler.",
    "Inter annotator agreement etiketleyiciler arası uyumu ölçer.",
    "Cohort data belirli gruplara ayrılmış veri setidir.",
    "Data enrichment dış kaynaklarla veriyi zenginleştirir.",
    "Feature store özelliklerin merkezi olarak saklandığı yapıdır.",
    "Data catalog veri varlıklarının listelendiği sistemdir.",
    "Metadata data hakkında bilgi içeren veridir.",
    "Schema veri yapısını tanımlar.",
    "Schema drift veri yapısının zamanla değişmesidir.",
    "Data integrity verinin tutarlılığını ifade eder.",
    "Data validation verinin kurallara uygunluğunu kontrol eder.",
    "Data cleaning hatalı verileri düzeltme sürecidir.",
    "Data preprocessing model için veri hazırlama sürecidir.",
    "Exploratory data analysis veri setini anlamayı sağlar.",
    "EDA veri dağılımını ve ilişkileri incelemek için kullanılır.",
    "Correlation analysis değişkenler arasındaki ilişkiyi ölçer.",
    "Feature correlation yüksek olduğunda multicollinearity oluşabilir.",
    "Data pipeline failures veri akışında sorunlara neden olabilir.",
    "Data pipeline monitoring sistemin sağlığını izler.",
    "Data refresh veri setinin güncellenmesidir.",
    "Incremental data yeni eklenen veriyi ifade eder.",
    "Historical data geçmiş kayıtları içerir.",
    "Training data modelin öğrenme verisidir.",
    "Ground truth gerçek etiketleri ifade eder.",
    "Label noise yanlış etiketlenmiş veridir.",
    "Data sparsity veri içinde çok fazla boşluk olmasıdır.",
    "High dimensional data çok sayıda feature içeren veridir.",
    "Curse of dimensionality yüksek boyutun getirdiği zorluktur.",
    "Data compression veriyi daha küçük hale getirme işlemidir.",
    "Feature hashing yüksek boyutlu veriyi azaltır.",
    "Vectorization metni sayısal forma çevirir.",
    "Tokenization veriyi anlamlı parçalara böler.",
    "Sequence data sıralı veri tipidir.",
    "Context window modelin görebildiği veri aralığıdır.",
    "Data augmentation pipeline veri çeşitliliğini artırır.",
    "Balanced dataset sınıf dağılımı dengeli veridir.",
    "Imbalanced learning dengesiz veriyle öğrenme sürecidir.",
    "Data drift monitoring veri değişimlerini takip eder.",
    "Continuous data flow kesintisiz veri akışıdır.",
    "Data preprocessing pipeline veri hazırlama adımlarını otomatikleştirir.",
    "Clean dataset model performansını artırır.",
    "High quality data daha iyi genelleme sağlar.",
"Veri tutarlılığı farklı kaynaklardan gelen bilgilerin uyumlu olmasını sağlar.",
    "Data reconciliation farklı veri setlerini karşılaştırarak uyumsuzlukları bulur.",
    "Veri standardizasyonu farklı formatlardaki veriyi ortak hale getirir.",
    "Data normalization sayısal değerleri aynı ölçeğe getirir.",
    "Veri temizleme süreci hatalı kayıtları düzeltmeyi içerir.",
    "Data profiling veri setinin istatistiksel özetini çıkarır.",
    "Veri keşfi ham veri içindeki yapıyı anlamayı sağlar.",
    "Exploratory analysis veri içindeki desenleri ortaya çıkarır.",
    "Veri kalitesi metrikleri completeness, accuracy ve consistency içerir.",
    "Completeness veri setindeki eksiksizliği ifade eder.",
    "Accuracy verinin gerçek değerlerle uyumunu gösterir.",
    "Consistency veriler arasında çelişki olmamasını sağlar.",
    "Timeliness verinin güncelliğini ifade eder.",
    "Validity verinin belirlenen kurallara uygunluğunu ölçer.",
    "Uniqueness tekrar eden kayıtların olmamasını sağlar.",
    "Data deduplication yinelenen verileri kaldırma işlemidir.",
    "Record linkage aynı varlığa ait kayıtları birleştirir.",
    "Entity resolution farklı kaynaklardaki aynı varlığı eşleştirir.",
    "Data merging farklı veri kaynaklarını birleştirme işlemidir.",
    "Data joining tablolar arasında ilişki kurmayı sağlar.",
    "Inner join sadece eşleşen kayıtları döndürür.",
    "Outer join tüm kayıtları birleştirir ve eksikleri doldurur.",
    "Left join sol tablodaki tüm verileri korur.",
    "Right join sağ tablodaki tüm verileri korur.",
    "Data transformation veriyi modelleme için uygun hale getirir.",
    "Feature transformation değişkenlerin matematiksel dönüşümünü içerir.",
    "Log transformation dağılımı daha normal hale getirir.",
    "Box-Cox transformation veri varyansını stabilize eder.",
    "Power transformation doğrusal olmayan veriyi düzenler.",
    "Discretization sürekli veriyi kategorilere böler.",
    "Binning veri aralıklarını gruplara ayırır.",
    "Data scaling modellerin öğrenmesini kolaylaştırır.",
    "Feature scaling algoritmaların performansını artırır.",
    "Robust scaling outlier etkisini azaltır.",
    "Min-max scaling veriyi 0 ile 1 arasına çeker.",
    "Standard scaling veriyi ortalama etrafında merkezler.",
    "Data pipeline veri akışını otomatik hale getirir.",
    "Streaming pipeline sürekli veri işleme sağlar.",
    "Batch pipeline veriyi toplu şekilde işler.",
    "ETL pipeline extract transform load adımlarından oluşur.",
    "ELT pipeline önce yükleyip sonra dönüştürür.",
    "Data ingestion veri sistemine giriş aşamasıdır.",
    "Data sink işlenmiş verinin kaydedildiği noktadır.",
    "Data source verinin geldiği kaynaktır.",
    "Data lake ham verinin saklandığı yerdir.",
    "Data warehouse analiz için optimize edilmiş yapıdır.",
    "Data mart belirli bir iş alanına özel veri deposudur.",
    "Operational data günlük işlemleri destekler.",
    "Analytical data analiz için kullanılan veridir.",
    "Real time ingestion anlık veri akışını işler.",
    "Event driven data olay bazlı veri üretir.",
    "Log data sistem aktivitelerini kaydeder.",
    "Telemetry data sistem performansını izler.",
    "Sensor data fiziksel cihazlardan gelen veridir.",
    "IoT data nesnelerin internetinden gelen veridir.",
    "Data labeling veri setine etiket ekleme işlemidir.",
    "Annotation quality model başarısını etkiler.",
    "Label consistency aynı veriye tutarlı etiket verilmesidir.",
    "Weak labels tam doğruluk gerektirmeyen etiketlerdir.",
    "Noisy labels hatalı etiketlenmiş veridir.",
    "Clean labels doğru ve güvenilir etiketlerdir.",
    "Self labeling modelin kendi verisini etiketlemesidir.",
    "Pseudo labeling model tahminlerini etiket olarak kullanır.",
    "Active learning modelin en önemli verileri seçmesidir.",
    "Human annotation insan tarafından yapılan etiketlemedir.",
    "Crowd labeling çok sayıda insanla etiketleme yapılmasıdır.",
    "Annotation tool veri etiketleme yazılımıdır.",
    "Label schema etiketlerin yapısını tanımlar.",
    "Data schema veri alanlarının düzenini belirler.",
    "Schema validation veri yapısını kontrol eder.",
    "Data contract veri üretici ve tüketici arasındaki anlaşmadır.",
    "Data governance veri yönetim kurallarını tanımlar.",
    "Data ownership verinin sorumlusunu belirtir.",
    "Data stewardship veri kalitesinden sorumlu roldür.",
    "Master data kritik iş verisini temsil eder.",
    "Reference data standart değer setleridir.",
    "Metadata management veri hakkında bilgiyi yönetir.",
    "Data observability veri sisteminin izlenebilirliğidir.",
    "Data monitoring veri akışının kontrolüdür.",
    "Pipeline monitoring veri süreçlerini izler.",
    "Data anomaly detection olağandışı veri noktalarını bulur.",
    "Statistical outlier detection istatistiksel yöntemlerle aykırı değer bulur.",
    "Z-score filtering uç değerleri tespit eder.",
    "IQR filtering çeyrekler arası aralık kullanır.",
    "Data skewness veri dağılımının asimetrisini ölçer.",
    "Data kurtosis veri dağılımının sivriliğini ölçer.",
    "Histogram analysis veri dağılımını görselleştirir.",
    "Density estimation veri yoğunluğunu tahmin eder.",
    "Sampling bias veri seçiminin temsil gücünü bozar.",
    "Data drift detection model performansını korumak için kullanılır.",
    "Feature drift özellik dağılımının değişmesidir.",
    "Label drift hedef değişken dağılımının değişmesidir.",
    "Concept drift veri ile hedef arasındaki ilişkinin değişmesidir.",
    "Data versioning veri setlerinin farklı sürümlerini yönetir.",
    "Dataset lineage verinin geçmişini takip eder.",
    "Data reproducibility aynı veriyle aynı sonucu üretmeyi sağlar.",
    "Dataset caching veri erişimini hızlandırır.",
    "Data compression depolama alanını azaltır.",
    "Lossless compression veri kaybı olmadan sıkıştırma yapar.",
    "Lossy compression bazı bilgileri kaybederek sıkıştırır.",
    "Feature store merkezi özellik yönetimi sağlar.",
    "Data catalog veri varlıklarını listeler.",
    "Data discovery veri setlerini bulmayı kolaylaştırır.",
    "Data indexing veri erişimini hızlandırır.",
    "Query optimization veri sorgularını hızlandırır.",
    "Partitioning veri setini parçalara ayırır.",
    "Sharding büyük veri setlerini dağıtır.",
    "Distributed storage veriyi birden fazla sunucuda saklar.",
    "Data replication veri yedeklemesi sağlar.",
    "Fault tolerance veri sistemlerinin dayanıklılığıdır.",
    "Data pipeline reliability sistem kararlılığını ifade eder.",
    "Data freshness verinin güncelliğini ölçer.",
    "Latency data sistem gecikmesini ifade eder.",
    "Throughput data işleme kapasitesini gösterir.",
    "Scalable data systems büyüyen veriyle başa çıkabilir.",
    "High volume data büyük miktarda veri anlamına gelir.",
    "High velocity data hızlı akan veri türüdür.",
    "High variety data farklı türde verileri içerir.",
    "Big data üç V prensibi ile tanımlanır.",
    "Data ecosystem veri bileşenlerinin bütünüdür.",
    "Data lifecycle veri üretiminden silinmesine kadar olan süreçtir.",
    "Data retention policy verinin ne kadar saklanacağını belirler.",
    "Data deletion verinin sistemden kaldırılmasıdır.",
    "Data archival eski verilerin saklanmasıdır.",
    "Cold data nadiren erişilen veridir.",
    "Hot data sık erişilen veridir.",
    "Warm data orta seviyede erişilen veridir.",
    "Data pipeline orchestration süreçlerin yönetimini sağlar.",
    "Workflow scheduling veri işleme adımlarını planlar.",
    "Data quality checks veri doğruluğunu kontrol eder.",
    "Automated data validation hataları otomatik tespit eder.",
    "Data SLA veri hizmet seviyesini tanımlar.",
    "Data reliability engineering veri sistemlerinin güvenilirliğini artırır.",
    "Clean pipeline hatasız veri akışı sağlar.",
    "Robust dataset hatalara dayanıklı veri setidir.",
    "Production data gerçek sistemlerden gelen veridir.",
    "Training dataset model öğrenmesi için hazırlanır.",
"Data kelimesi İngilizcede veri anlamına gelir.",
    "Veri yani data makine öğrenmesinin temel girdisidir.",
    "Data preprocessing veri hazırlama sürecini ifade eder.",
    "Ham data doğrudan modele verilmeden önce işlenmelidir.",
    "Dataset kelimesi veri kümesi anlamına gelir.",
    "Bir dataset çok sayıda data sample içerir.",
    "Data sample tek bir veri örneğini ifade eder.",
    "Label kelimesi veri etiketi anlamına gelir.",
    "Labeled data etiketlenmiş veri demektir.",
    "Unlabeled data etiketsiz veri anlamına gelir.",
    "Data cleaning veri temizleme sürecidir.",
    "Dirty data hatalı veya eksik veri anlamına gelir.",
    "Clean data model eğitimi için uygun veridir.",
    "Data quality veri kalitesini ifade eder.",
    "High quality data daha iyi model sonuçları üretir.",
    "Low quality data model performansını düşürür.",
    "Data pipeline veri işleme hattı anlamına gelir.",
    "Pipeline kelimesi ardışık işlem sürecini ifade eder.",
    "ETL pipeline veri çıkarma, dönüştürme ve yükleme sürecidir.",
    "Data ingestion verinin sisteme alınmasıdır.",
    "Ingestion kelimesi veri içe aktarma anlamına gelir.",
    "Data storage verinin saklanmasıdır.",
    "Storage kelimesi depolama anlamına gelir.",
    "Data lake ham verinin saklandığı yerdir.",
    "Data warehouse analiz için hazırlanmış veri deposudur.",
    "Warehouse kelimesi depo anlamına gelir.",
    "Structured data düzenli veri anlamına gelir.",
    "Unstructured data düzensiz veri anlamına gelir.",
    "Semi structured data yarı düzenli veri demektir.",
    "Tabular data tablo formatındaki veridir.",
    "Time series data zaman serisi verisidir.",
    "Streaming data akan veri anlamına gelir.",
    "Batch data toplu işlenen veri demektir.",
    "Real time data anlık veri anlamına gelir.",
    "Data labeling veri etiketleme işlemidir.",
    "Labeling annotation süreci olarak da bilinir.",
    "Annotation kelimesi açıklama veya etiketleme anlamına gelir.",
    "Human annotation insan tarafından yapılan etiketlemedir.",
    "Auto labeling otomatik veri etiketlemedir.",
    "Data augmentation veri artırma yöntemidir.",
    "Augmentation kelimesi çoğaltma anlamına gelir.",
    "Synthetic data yapay olarak üretilen veridir.",
    "Synthetic kelimesi yapay anlamına gelir.",
    "Data sampling veri örnekleme işlemidir.",
    "Sampling kelimesi örnekleme anlamına gelir.",
    "Random sampling rastgele veri seçimi demektir.",
    "Stratified sampling dengeli veri seçimi sağlar.",
    "Data bias veri yanlılığı anlamına gelir.",
    "Bias kelimesi önyargı anlamında kullanılır.",
    "Sampling bias hatalı veri seçimi demektir.",
    "Data leakage veri sızıntısı anlamına gelir.",
    "Leakage modelin yanlış bilgi öğrenmesidir.",
    "Train data eğitim verisi anlamına gelir.",
    "Test data test verisi demektir.",
    "Validation data doğrulama verisidir.",
    "Split data veri bölme işlemidir.",
    "Train test split veri setini ikiye ayırır.",
    "Cross validation çapraz doğrulama anlamına gelir.",
    "K fold cross validation veri parçalama yöntemidir.",
    "Data normalization veri ölçeklendirme işlemidir.",
    "Normalization kelimesi normalize etme anlamına gelir.",
    "Standardization standartlaştırma demektir.",
    "Scaling veri değerlerini ölçekleme işlemidir.",
    "Min max scaling veriyi 0 ile 1 arasına çeker.",
    "Data transformation veri dönüştürme işlemidir.",
    "Transformation kelimesi dönüşüm anlamına gelir.",
    "Feature engineering özellik üretme sürecidir.",
    "Feature kelimesi özellik anlamına gelir.",
    "Feature selection özellik seçme işlemidir.",
    "Feature extraction özellik çıkarımıdır.",
    "Data representation veri temsilidir.",
    "Vector representation verinin vektör formudur.",
    "Embedding representation yoğun vektör gösterimidir.",
    "Embedding kelimesi gömme anlamına gelir.",
    "Vectorization veriyi vektöre çevirme işlemidir.",
    "Encoding veriyi sayısal hale getirme işlemidir.",
    "One hot encoding kategorik veriyi dönüştürür.",
    "Label encoding etiketleri sayıya çevirir.",
    "Data schema veri yapısı anlamına gelir.",
    "Schema verinin şemasıdır.",
    "Metadata veri hakkında bilgi veren veridir.",
    "Data catalog veri kataloğudur.",
    "Data lineage verinin kökenini gösterir.",
    "Lineage kelimesi soy ağacı anlamına gelir.",
    "Data governance veri yönetimi anlamına gelir.",
    "Governance kelimesi yönetişim demektir.",
    "Data ownership veri sahipliği anlamına gelir.",
    "Data privacy veri gizliliği demektir.",
    "Privacy kelimesi mahremiyet anlamına gelir.",
    "Data anonymization veriyi anonim hale getirme işlemidir.",
    "Anonymization kimlik gizleme anlamına gelir.",
    "PII personally identifiable information demektir.",
    "Sensitive data hassas veri anlamına gelir.",
    "Data compliance yasal uyumluluk anlamına gelir.",
    "Compliance kurallara uyum demektir.",
    "GDPR veri koruma yasasıdır.",
    "Data quality checks veri kontrol adımlarıdır.",
    "Validation data doğrulama verisidir.",
    "Data integrity veri bütünlüğü anlamına gelir.",
    "Integrity tutarlılık ve doğruluk demektir.",
    "Data consistency veri tutarlılığıdır.",
    "Consistency uyumluluk anlamına gelir.",
    "Data accuracy veri doğruluğudur.",
    "Accuracy doğruluk anlamına gelir.",
    "Data completeness veri tamlığıdır.",
    "Completeness eksiksizlik demektir.",
    "Data timeliness verinin güncelliğidir.",
    "Timeliness zamanlılık anlamına gelir.",
    "Data freshness verinin ne kadar güncel olduğunu gösterir.",
    "Freshness tazelik anlamına gelir.",
    "Data monitoring veri izleme işlemidir.",
    "Monitoring sürekli kontrol anlamına gelir.",
    "Data drift veri değişimi anlamına gelir.",
    "Concept drift model ilişkilerinin değişmesidir.",
    "Drift detection değişim tespitidir.",
    "Data versioning veri sürümleme işlemidir.",
    "Versioning sürüm yönetimi demektir.",
    "Dataset version veri seti sürümüdür.",
    "Data reproducibility tekrar üretilebilirliktir.",
    "Reproducibility aynı sonucu yeniden elde etmektir.",
    "Data pipeline orchestration süreç yönetimidir.",
    "Orchestration koordinasyon anlamına gelir.",
    "Workflow data iş akışıdır.",
    "Data lifecycle veri yaşam döngüsüdür.",
    "Lifecycle yaşam döngüsü anlamına gelir.",
    "Data deletion veri silme işlemidir.",
    "Data archival veri arşivleme işlemidir.",
    "Archival uzun süreli saklama demektir.",
    "Hot data sık kullanılan veri anlamına gelir.",
    "Cold data nadir kullanılan veri demektir.",
    "Data compression veri sıkıştırma işlemidir.",
    "Compression sıkıştırma anlamına gelir.",
    "Lossless compression kayıpsız sıkıştırmadır.",
    "Lossy compression kayıplı sıkıştırmadır.",
    "Data retrieval veri erişimi anlamına gelir.",
    "Retrieval geri getirme demektir.",
    "Data indexing veri indeksleme işlemidir.",
    "Indexing hızlı erişim sağlar.",
    "Query data sorgulama anlamına gelir.",
    "Query optimization sorgu iyileştirmedir.",
    "Data partitioning veri bölümlendirme işlemidir.",
    "Partitioning parçalama anlamına gelir.",
    "Distributed data dağınık veri sistemidir.",
    "Replication veri kopyalama işlemidir.",
    "Fault tolerance hata toleransı demektir.",
    "Data reliability veri güvenilirliğidir.",
    "Reliability güvenilirlik anlamına gelir.",
    "Data scalability ölçeklenebilirliktir.",
    "Scalability büyüyebilme yeteneğidir.",
    "Big data büyük veri anlamına gelir.",
    "Volume data miktarını ifade eder.",
    "Velocity veri hızını ifade eder.",
    "Variety veri çeşitliliğini ifade eder.",
    "Data ecosystem veri ekosistemidir.",
    "Ecosystem sistem bütünüdür."

]

# ==========================================
# 2. TOKENİZASYON VE VERİ ÖN İŞLEME
# ==========================================
# Keras Tokenizer nesnesini başlatıyoruz.
tokenizer = Tokenizer()
# Sözlüğü verideki benzersiz kelimelerle dolduruyoruz.
tokenizer.fit_on_texts(texts)
# ÖNEMLİ: Toplam kelime sayısına 1 ekliyoruz çünkü Keras, padding (0)
# karakterini de sözlüğün bir elemanı olarak sayar. Matematiksel matris boyutu için şarttır.
total_words = len(tokenizer.word_index) + 1
print(f"Sözlükteki Benzersiz Kelime Sayısı (+1 Pad dahil): {total_words}")


# ==========================================
# 3. N-GRAM DİZİLERİNİN OLUŞTURULMASI
# ==========================================
input_sequences=[]
for text in texts:
    # Cümleyi sayısal index listesine çeviriyoruz. Örn: [5, 12, 45, 3]
    token_list=tokenizer.texts_to_sequences([text])[0]
    # Kelime sayısı kadar kayan pencere ile alt diziler (N-gram) üretiyoruz.
    for i in range(1,len(token_list)):
        n_gram_sequences=token_list[:i+1]
        input_sequences.append(n_gram_sequences)

# Modelin kabul edeceği maksimum uzunluğu buluyoruz (En uzun cümlenin kelime sayısı).
max_sequence_length=max(len(x) for x in input_sequences)
print(f"En Uzun Dizinin (Cümlenin) Kelime Sayısı: {max_sequence_length}")

# ==========================================
# 4. PADDING (BOYUT SABİTLEME) İŞLEMİ
# ==========================================
# Tüm alt dizileri en uzun dizi boyutuna eşitliyoruz.
# padding="pre" -> Kısa olan dizilerin ÖNÜNE sıfır (0) ekler.
# LSTM modellerinde bilgi sondaki kelimelerde biriktiği için "pre" (önden) doldurma daha yüksek başarı verir.
input_sequences=pad_sequences(input_sequences,maxlen=max_sequence_length, padding="pre")


# ==========================================
# 5. GİRDİ (X) VE HEDEF (y) AYIRMA & ONE-HOT ENCODING
# ==========================================
# X: Her satırın son elemanı hariç tüm elemanları (Girdi dizisi)
# Örn matris dilimleme mantığı: [:, :-1] -> Tüm satırları al, sütunlarda sondan bir öncekine kadar git.
X=input_sequences[:,: -1]
# y: Her satırın sadece son elemanı (Tahmin edilmesi gereken hedef kelime)
# [:, -1] -> Tüm satırları al, sadece en son sütunu çek.
y=input_sequences[:,-1]

# Çoklu sınıflandırma (Sözlükteki N kelimeden birini tahmin etme) yapacağımız için
# hedef etiketleri One-Hot matrisine dönüştürüyoruz.
# Örn: Kelime ID'si 3 ise bunu [0, 0, 0, 1, 0, 0... 0] şekline getirir.
y=tf.keras.utils.to_categorical(y,num_classes=total_words)

# ==========================================
# 6. LSTM TABANLI MODEL MİMARİSİ
# ==========================================

model=Sequential()

#Embedding Katmanı
# ARGÜMAN 1: total_words -> Girecek kelime (indeks) havuzunun boyutu.
# ARGÜMAN 2: 50 -> Çıktı vektör boyutu. Her sayısal kelime ID'si arka planda 50 boyutlu anlamsal bir vektöre çevrilir.
# ARGÜMAN 3: input_length=X.shape[1] -> Giriş matrisinin sabit uzunluğu (Yani max_sequence_length - 1)
model.add(Embedding(total_words, 50, input_length=X.shape[1]))

#LSTM Katmanı
# ARGÜMAN 1: 100 -> Gizli katmandaki LSTM hücre (nöron) sayısı. Modelin hafıza kapasitesidir.
# ARGÜMAN 2: return_sequences=False -> Sadece dizinin en sonundaki tahmini bir sonraki katmana aktarır.
model.add(LSTM(100, return_sequences= False))

#Çıkış Katmanı
# ARGÜMAN 1: total_words -> Çıkış katmanında sözlükteki her kelime için bir nöron olmalıdır.
# ARGÜMAN 2: activation='softmax' -> Tüm nöronların çıktı değerlerini 0 ile 1 arasında olasılıklara dönüştürür.
# Tüm çıkış olasılıklarının toplamı tam olarak 1.0 eder.
model.add(Dense(total_words,activation='softmax'))

#Olasılık tahmini (Çoklu Sınıflandırma) yaptığımız için loss fonksiyonu 'categorical_crossentropy' seçildi.
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

# ==========================================
# 7. MODELİN EĞİTİLMESİ
# ==========================================
# Modelin kelime geçişlerini ezberleyip örüntüyü kavrayabilmesi için epoch sayısını 100 tutuyoruz.
model.fit(X,y,epochs=100,verbose=1)

# ==========================================
# 8. YENİ METİN ÜRETİM (TEXT GENERATION) FONKSİYONU
# ==========================================
def generate_text(seed_text,next_word):
    """
        seed_text  : Modelin cümleye başlayacağı tetikleyici kelime(ler) (String)
        next_word : Modelin peş peşe üreteceği kelime sayısı (Integer)
    """
    for _ in range(next_word):
        # 1. Adım: Kullanıcının girdi olarak verdiği metni sayısal indeks listesine çevir.
        token_list = tokenizer.texts_to_sequences([seed_text])[0]

        # 2. Adım: Girdiyi modelin eğitildiği boyuta getirmek için önden sıfırlarla doldur (Padding).
        # max_sequence_length - 1 yapıyoruz çünkü girdilerimiz (X) hedef kelime çıktığı için 1 birim daha kısaydı.
        token_list = pad_sequences([token_list], maxlen=max_sequence_length - 1, padding="pre")

        # 3. Adım: Modeli çalıştır ve sözlükteki tüm kelimeler için olasılık dağılım matrisini al.
        predicted_prob = model.predict(token_list, verbose=0)

        # 4. Adım: Olasılık matrisindeki en yüksek değere (en yüksek ihtimalli kelimeye) sahip olan indeksi bul.
        predicted_word_index = np.argmax(predicted_prob, axis=-1)

        # 5. Adım: Bulunan sayısal indeksi Keras sözlüğünden geri kelimeye (String) çevir.
        predicted_word = tokenizer.index_word[predicted_word_index[0]]

        # 6. Adım: Üretilen kelimeyi bir sonraki adımda girdi olarak kullanmak üzere ana metnin sonuna ekle.
        seed_text = seed_text + " " + predicted_word

    return seed_text

# ==========================================
# 9. MODELİ TEST ETME
# ==========================================
# Veri setimiz yazılım odaklı olduğu için yazılımla ilgili kelimelerle başlatıyoruz.
print("\n--- Test 1 ---")
print(generate_text(seed_text="Veri", next_word=6))

print("\n--- Test 2 ---")
print(generate_text(seed_text="data preprocessing", next_word=7))

print("\n--- Test 3 ---")
print(generate_text(seed_text="makine öğrenmesi", next_word=4))